# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='apartment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='core.Apartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_contracts', to='core.Tenant'),
        ),
    ]
